### PR TITLE
Delete images in batches of up to 100

### PR DESCRIPTION
**Pull request by ags**
The ECR BatchDeleteImage does not support deleting batches of more than
100 images. When attempting to do so, the tool panics like so:

```
panic: InvalidParameterException: Invalid parameter at 'imageIds' failed
to satisfy constraint: 'Member must have length less than or equal to
100'
```

This should change the deletes to be performed in batches of up to 100,
which should avoid the API limit.

See https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_BatchDeleteImage.html

### CODE REVIEW

**Comment by pda** [comment]
Nice, thanks @ags 👍

**Comment by ags** [comment]
Thanks @pda :) Any chance of pushing out a new release?

**Comment by pda** [comment]
Sure. Wish I could remember how I built the previous release.

**Comment by pda** [comment]
Done: https://github.com/99designs/aws-ecr-gc/releases/tag/v1.0.1
And I [hacked together a Makefile](https://github.com/99designs/aws-ecr-gc/commit/c81670bb87ec7eb46d78451892c5ec8298061a98) so I don't forget how to release next time.

**Comment by ags** [comment]
Thanks! 👍

**Pull request merged**
